[REM] base_location: remove script migration to allow migration from 11.0 major version Otherwise during the update we get the following errror:
2023-09-15 15:13:50,252 1 INFO bexsol16_2023-08-28 odoo.modules.migration: module base_location: Running migration [>13.0.1.0.0] pre-migration
2023-09-15 15:13:50,254 1 ERROR bexsol16_2023-08-28 odoo.sql_db: bad query: UPDATE res_partner rp
        SET city_id = rcz.city_id
        FROM res_city_zip rcz
        WHERE rp.city_id IS NULL AND rp.zip_id = rcz.id
ERROR: relation "res_city_zip" does not exist
LINE 3:         FROM res_city_zip rcz
                     ^

2023-09-15 15:13:50,261 1 WARNING bexsol16_2023-08-28 odoo.modules.loading: Transient module states were reset
2023-09-15 15:13:50,262 1 ERROR bexsol16_2023-08-28 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/addons/base_location/migrations/13.0.1.0.0/pre-migration.py", line 10, in migrate
    cr.execute(
  File "/srv/odoo/.pyenv/versions/3.10.8/lib/python3.10/site-packages/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "res_city_zip" does not exist
LINE 3:         FROM res_city_zip rcz
                     ^